# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  config: "config"
  lang: "tr"
  treebank: "FrameNet"
  train_name: "tr_framenet-ud-train"
  dev_name: "tr_framenet-ud-dev"
  test_name: "tr_framenet-ud-test"
  gpu: -1

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["corpus", "training", "metrics"]

workflows:
  all:
    - train
    - evaluate

commands:
  - name: train
    help: "Train ${vars.treebank}"
    script:
      - "python -m spacy train ${vars.config}.cfg --output training/${vars.treebank} --gpu-id ${vars.gpu} --paths.train corpus/${vars.treebank}/${vars.train_name}.spacy --paths.dev corpus/${vars.treebank}/${vars.dev_name}.spacy --nlp.lang=${vars.lang}"
    deps:
      - "corpus/${vars.treebank}/${vars.train_name}.spacy"
      - "corpus/${vars.treebank}/${vars.dev_name}.spacy"
      - "${vars.config}.cfg"
    outputs:
      - "training/${vars.treebank}/model-best"

  - name: evaluate
    help: "Evaluate on the test data and save the metrics"
    script:
      - "python -m spacy evaluate ./training/${vars.treebank}/model-best ./corpus/${vars.treebank}/${vars.test_name}.spacy --output ./metrics/${vars.treebank}.json --gpu-id ${vars.gpu}"
    deps:
      - "training/${vars.treebank}/model-best"
      - "corpus/${vars.treebank}/${vars.test_name}.spacy"
    outputs:
      - "metrics/${vars.treebank}.json"

  - name: clean
    help: "Remove intermediate files"
    script:
      - "rm -rf training/*"
      - "rm -rf metrics/*"
      - "rm -rf corpus/*"


